package lt.vu.usecases.mybatis.mydao;

import java.util.List;
import lt.vu.usecases.mybatis.mymodel.Cable;
import org.mybatis.cdi.Mapper;


@Mapper
public interface CableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CABLE
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CABLE
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    int insert(Cable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CABLE
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    Cable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CABLE
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    List<Cable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CABLE
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    int updateByPrimaryKey(Cable record);
}