package lt.vu.usecases.mybatis.mydao;

import java.util.List;
import lt.vu.usecases.mybatis.mymodel.Computer;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ComputerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPUTER
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPUTER
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    int insert(Computer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPUTER
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    Computer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPUTER
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    List<Computer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPUTER
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    int updateByPrimaryKey(Computer record);
}