package lt.vu.usecases.mybatis.mydao;

import java.util.List;
import lt.vu.usecases.mybatis.mymodel.Lectureroom;
import org.mybatis.cdi.Mapper;

@Mapper
public interface LectureroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTUREROOM
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTUREROOM
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    int insert(Lectureroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTUREROOM
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    Lectureroom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTUREROOM
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    List<Lectureroom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTUREROOM
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    int updateByPrimaryKey(Lectureroom record);
}