CREATE TABLE IF NOT EXISTS LECTUREROOM
(
	ID INTEGER NOT NULL IDENTITY,
	TITLE            VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS COMPUTER
(
  ID INTEGER NOT NULL IDENTITY,
  ROOMID           INTEGER,
  MODEL            VARCHAR(50),
  FOREIGN KEY (ROOMID) REFERENCES LECTUREROOM (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CABLE
(
  ID INTEGER NOT NULL IDENTITY,
  CONNECTIONTYPE    VARCHAR(50),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CABLECONNECTION
(
  ROOMID    INTEGER,
  CABLEID   INTEGER,
  PRIMARY KEY (ROOMID, CABLEID),
  FOREIGN KEY (ROOMID) REFERENCES LECTUREROOM (ID),
  FOREIGN KEY (CABLEID) REFERENCES CABLE (ID)
);