/*Jei sukurti in-memory H2 db*/
CREATE TABLE IF NOT EXISTS LECTUREROOM
(
	ID INTEGER NOT NULL IDENTITY,
	TITLE            VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CHAIR
(
  ID INTEGER NOT NULL IDENTITY,
  ROOMID           INTEGER,
  MAKER            VARCHAR(50),
  FOREIGN KEY (ROOMID) REFERENCES LECTUREROOM (ID),
  PRIMARY KEY (ID)
);