package lt.vu.usecases.mybatis.mymodel;

public class Cableconnection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CABLECONNECTION.ROOMID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    private Integer roomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CABLECONNECTION.CABLEID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    private Integer cableid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CABLECONNECTION.ROOMID
     *
     * @return the value of PUBLIC.CABLECONNECTION.ROOMID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CABLECONNECTION.ROOMID
     *
     * @param roomid the value for PUBLIC.CABLECONNECTION.ROOMID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CABLECONNECTION.CABLEID
     *
     * @return the value of PUBLIC.CABLECONNECTION.CABLEID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public Integer getCableid() {
        return cableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CABLECONNECTION.CABLEID
     *
     * @param cableid the value for PUBLIC.CABLECONNECTION.CABLEID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public void setCableid(Integer cableid) {
        this.cableid = cableid;
    }
}