package lt.vu.usecases.mybatis.mymodel;

public class Cable {
    /**
     *1sec
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CABLE.ID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CABLE.CONNECTIONTYPE
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    private String connectiontype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CABLE.ID
     *
     * @return the value of PUBLIC.CABLE.ID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CABLE.ID
     *
     * @param id the value for PUBLIC.CABLE.ID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CABLE.CONNECTIONTYPE
     *
     * @return the value of PUBLIC.CABLE.CONNECTIONTYPE
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public String getConnectiontype() {
        return connectiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CABLE.CONNECTIONTYPE
     *
     * @param connectiontype the value for PUBLIC.CABLE.CONNECTIONTYPE
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public void setConnectiontype(String connectiontype) {
        this.connectiontype = connectiontype;
    }
}