package lt.vu.usecases.mybatis.mymodel;

public class Computer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.ROOMID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    private Integer roomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.MODEL
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    private String model;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.ID
     *
     * @return the value of PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.ID
     *
     * @param id the value for PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.ROOMID
     *
     * @return the value of PUBLIC.COMPUTER.ROOMID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.ROOMID
     *
     * @param roomid the value for PUBLIC.COMPUTER.ROOMID
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.MODEL
     *
     * @return the value of PUBLIC.COMPUTER.MODEL
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.MODEL
     *
     * @param model the value for PUBLIC.COMPUTER.MODEL
     *
     * @mbg.generated Tue Apr 17 01:41:30 EEST 2018
     */
    public void setModel(String model) {
        this.model = model;
    }
}